item {
  name: "/m/01g317"
  id: 1
  display_name: "rov"
}
item {
  name: "/m/0199g"
  id: 2
  display_name: "plant"
}
item {
  name: "/m/0k4j"
  id: 3
  display_name: "animal_fish"
}
item {
  name: "/m/04_sv"
  id: 4
  display_name: "animal_starfish"
}
item {
  name: "/m/05czz6l"
  id: 5
  display_name: "animal_shells"
}
item {
  name: "/m/01bjv"
  id: 6
  display_name: "animal_crab"
}
item {
  name: "/m/07jdr"
  id: 7
  display_name: "animal_eel"
}
item {
  name: "/m/07r04"
  id: 8
  display_name: "animal_etc"
}
item {
  name: "/m/019jd"
  id: 9
  display_name: "trash_clothing"
}
item {
  name: "/m/015qff"
  id: 10
  display_name: "trash_pipe"
}
item {
  name: "/m/01pns0"
  id: 11
  display_name: "trash_bottle"
}
item {
  name: "/m/02pv19"
  id: 12
  display_name: "trash_bag"
}
item {
  name: "/m/015qbp"
  id: 13
  display_name: "trash_snackwrapper"
}
item {
  name: "/m/0cvnqh"
  id: 14
  display_name: "trash_can"
}
item {
  name: "/m/015p6"
  id: 15
  display_name: "trash_cup"
}
item {
  name: "/m/01yrx"
  id: 16
  display_name: "trash_container"
}
item {
  name: "/m/0bt9lr"
  id: 17
  display_name: "trash_unknown_instance"
}
item {
  name: "/m/03k3r"
  id: 18
  display_name: "trash_branch"
}
item {
  name: "/m/07bgp"
  id: 19
  display_name: "trash_wreckage"
}
item {
  name: "/m/01xq0k1"
  id: 20
  display_name: "trash_tarp"
}
item {
  name: "/m/0bwd_0j"
  id: 21
  display_name: "trash_rope"
}
item {
  name: "/m/01dws"
  id: 23
  display_name: "trash_net"
}
